// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_100000_points = "CgkI65epmNEWEAIQBA"; // <GPGSID>
        public const string leaderboard_score_leaderboard = "CgkI65epmNEWEAIQAg"; // <GPGSID>
        public const string achievement_1000000_points = "CgkI65epmNEWEAIQBQ"; // <GPGSID>
        public const string achievement_5000000_points = "CgkI65epmNEWEAIQBg"; // <GPGSID>
        public const string achievement_thanks_for_playing = "CgkI65epmNEWEAIQAQ"; // <GPGSID>
        public const string achievement_10000_points = "CgkI65epmNEWEAIQAw"; // <GPGSID>
        public const string achievement_10000000_points = "CgkI65epmNEWEAIQBw"; // <GPGSID>

}

